apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: {{ .Values.postgresUser | b64enc | quote }}
  postgres-password: {{ .Values.postgresPassword | b64enc | quote }}