apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-helm-chart.fullname" . }}
  labels:
    app: {{ include "postgres-helm-chart.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "postgres-helm-chart.name" . }}